Create class structure for characters
ViktorWase/StureJerDettEejen pull request #1
Opened 2020-10-10 07:05 UTC by ViktorWase

Tjoflöjt.

Jag har implementerat en klasstruktur för alla karaktärer nu. Den är inte perfekt, men nu blir det betydligt lättare att hålla koll på alla nya typer av karaktärer.

Problem:
1) De alignar inte i rutorna korrekt.
2) Power-ups fungerar inte längre, vilket leder till 
3) Jag har inte vågat ta bort all gammal kod än.

Ta gärna o läs igenom koden för att se om jag bör ändra något innan jag löser problemen ovan.
Ta o se om det funkar för er också.

2020-10-10 12:51 UTC, johntu requested changes
Verkar funka! Snyggt!
Lite problem med att slåss men det är nog kopplat till att karaktärer inte alignas mot gridet.
Har förståt det som att det också ska gå att inherita scener, men vet inte vad man skulle tjäna på det. Går ju att testa nån gång men tycker det här verkar toppen.

2020-10-10 12:51 UTC, johnbrynte commented on Character.gd
> +func _ready():
Här ska in en rad för att sätta start positionen och se till att dom fastnar mot gridet:
```
set_start_coordinates("få koordinater från tilemappen")
```

2020-10-10 12:51 UTC, johnbrynte commented on Character.gd
> +export(Alignment) var alignment = Alignment.undefined
Den här ska inte längre vara exponerad i editorn utan borde sättas i ready-funktionen (eller liknande) för varje script som extendar, som du redan gör. Risken annars är att man kan råka sätta en GoodCharacter till fel typ osv.

2020-10-10 12:51 UTC, johnbrynte commented on Enemy.gd
> +extends "res://Character.gd"
Lite otydlig naming för Enemy måste jag ändå säga. Om alla extendar Character och vi har GoodCharacter borde vi rimligtvis ha EvulCharacter. Gillar att det står explicit i namnet!

2020-10-10 12:51 UTC, johnbrynte commented on BasicGoon.tscn
> +[node name="KinematicBody2D" type="KinematicBody2D"]
"Varför KinematicBody2D?" vill jag fråga, men jag gissar vad svaret är.

Anledningen att vi använde det i kodexemplet var att det är bra för många spel där man hanterar basic movement där saker ska kollidera. Men eftersom vi sköter allt det själva bör vi bara använda en vanlig Node2D.

Vi får dessutom dom här härliga felmeddelandena i editorn
![Screenshot from 2020-10-10 13-44-43](https://user-images.githubusercontent.com/1489213/95654467-71146680-0b00-11eb-9664-4c289a5ee8a3.png)

2020-10-10 12:55 UTC, ViktorWase commented on BasicGoon.tscn
> +[node name="KinematicBody2D" type="KinematicBody2D"]
Mm, det har du rätt i. Tar o fixar det.

2020-10-10 13:17 UTC, ViktorWase commented on Character.gd
> +export(Alignment) var alignment = Alignment.undefined
Fixat.

2020-10-10 13:17 UTC, ViktorWase commented on Character.gd
> +func _ready():
_ready tar inte argument och klassen Character kan ju inte veta vilken karaktär den motsvarar för då kan den inte motsvara alla karaktärer. Ska jag lägga till en set_coordinates-funktion? Den skulle väl bara uppdatera cx och cy då, antar jag? Eller ska Character-klassen ha kännedom om hur stor en tile i tilemap är?

2020-10-10 13:17 UTC, ViktorWase commented on Enemy.gd
> +extends "res://Character.gd"
Mm, det är en bra poäng. Fixart.

2020-10-10 13:17 UTC, ViktorWase commented on BasicGoon.tscn
> +[node name="KinematicBody2D" type="KinematicBody2D"]
Det blev lite småkrångligt, så jag tar och fixar det en annan dag.

2020-10-10 14:01 UTC, johntu commented on Character.gd
> +func _ready():
Ja hur tänkte jag... det här kanske funkar som vanligt, för det är ju tilemap som ska initiera karaktärerna med set_coordinates. Du kan nog ignorera den här kommentaren.

2020-10-13 19:23 UTC, ViktorWase commented on BasicGoon.tscn
> +[node name="KinematicBody2D" type="KinematicBody2D"]
Nu ska det vara fixat.

2020-10-14 15:44 UTC, merged